### ISSUE TITLE
/api/register 404 not found

### ISSUE THREAD

**Issue by harshith-chowdary** [akashyap2013/MERN_Login_App_with_ResetEmail#5]
While trying to verify register using Thunder Cloud it shows Error 404 : /api/register not found please fix this

**Comment by musaCODEzz** [comment]
okay, so anyone going through this issue, i found the solution, apparently Mongoose doesn't accept callbacks in versions 7 and greater, they prefer to use aync/await or promises apparently as seen from google/stackoverflow. However the tutor has used version 6.8.0, which doesn't cause this issue yet. So my solution was to downgrade to mongoose which accepts callbacks, hence type in terminal "npm i mongoose@6.8.0" and it was fine to **go.******

**Comment by musaCODEzz** [comment]
> While trying to verify register using Thunder Cloud it shows Error 404 : /api/register not found please fix this

okay, so anyone going through this issue, i found the solution, apparently Mongoose doesn't accept callbacks in versions 7 and greater, they prefer to use aync/await or promises apparently as seen from google/stackoverflow. However the tutor has used version 6.8.0, which doesn't cause this issue yet. So my solution was to downgrade to mongoose which accepts callbacks, hence type in terminal "npm i mongoose@6.8.0" and it was fine to go.****

**Comment by varunsudrik** [comment]
Yes, i downgraded mongoose version and the code is working now.
if you need more information, visit the link below:
https://www.youtube.com/watch?v=dfeQuadvcB0
